config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :locations

  root 'locations#index'
  get  'cab_requests/receive_sms' => 'cab_requests#receive_sms'
  # get  'cab_requests/receive_sms_for_ride' => 'cab_requests#receive_sms_for_ride'
  # get  'cab_requests/receive_sms_for_driver_registration' => 'cab_requests#receive_sms_for_driver_registration'
  resources :cab_requests
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CabService" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">CabService</a>
          <div class="container nav-collapse">
            <ul class="nav  pull-right">
              <% if user_signed_in? %>
                <li>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
                </li>
              <% else %>
                <li>
                <%= link_to('Login', new_user_session_path)  %>  
                </li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <br/>
          <br/>
          <br/>
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>">
              <a href="#" data-dismiss="alert" class="close">×</a>
                <%= value %>    
            </div>
          <% end %>
          <% if user_signed_in? %>
          <div class="span3">
            <div class="well sidebar-nav ">
              <h3>Admin Tasks</h3>
              <ul class="nav nav-list">
                <li><%= link_to "List Locations", locations_path  %></li>
                <li><%= link_to "Add Location", new_location_path  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
          <%end%>
          <div class="span9">
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

<style type="text/css">
  .alert{
    text-align: center;
  }
  a:hover{
    background-color: transparent;
  }
</style>
  </body>
</html>